trigger:
- master

jobs:
- job: linux
  displayName: Build on Linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
   - checkout: self
   - bash: |
       pip3.6 install pep517
       python3.6 -m pep517.build --binary --out-dir wheelhouse .
- job: mac
  displayName: Build on macOS
  pool: {vmImage: 'macOS-10.14'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
   - checkout: self
   - bash: |
       pip3.6 install pep517
       python3.6 -m pep517.build --binary --out-dir wheelhouse .
- job: windows
  displayName: Build on Windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
   - script: git config --global core.symlinks true
   - checkout: self
   - powershell: |
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe -force
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.exe -force
     displayName: Remove extraneous Python Interpreters
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
   - bash: echo "##vso[task.prependpath]$(Build.SourcesDirectory)\\py_mini_racer\\extension\\depot_tools\\"
   - checkout: self
   - bash: |
       pip3.6 install pep517
       python3.6 -m pep517.build --binary --out-dir wheelhouse .
